name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base git zip

    - name: Compile project
      run: |
        make clean opl.elf
        make IGS=1 clean opl.elf
        make PADEMU=1 clean opl.elf
        make IGS=1 PADEMU=1 clean opl.elf
        make DEBUG=1 clean opl.elf
        make DEBUG=1 IOPCORE_DEBUG=1 clean opl.elf
        make DEBUG=1 EESIO_DEBUG=1 clean opl.elf
        make DEBUG=1 INGAME_DEBUG=1 clean opl.elf
        make clean release

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: OPNPS2LD-${{ steps.slug.outputs.sha8 }}
        path: OPNPS2LD-*.ZIP
