name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2sdk-ports:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base git zlib-dev ucl-dev
        git clone https://github.com/ps2dev/ps2-packer
        cd ps2-packer
        make all install
        cd ..

    - name: Compile project
      run: |
        make clean release
